#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 06 19:42:30 IST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 981cbd36290944088304fd9ba207ae98 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lookAheadCarryGenerator_behav xil_defaultlib.lookAheadCarryGenerator xil_defaultlib.glbl -log elaborate.log"
xelab -wto 981cbd36290944088304fd9ba207ae98 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot lookAheadCarryGenerator_behav xil_defaultlib.lookAheadCarryGenerator xil_defaultlib.glbl -log elaborate.log

